name: Example workflow using Snyk
on: push_request
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: 070fdaf6-69e6-456d-bfe6-de8b1cab0615
